# serverless.yml

service: aws-ip-range-api # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage,'prod'}
  region: us-east-2
  environment:
    LOGGER_LEVEL: "DEBUG" # CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET
    IP_RANGE_JSON_URL: "https://ip-ranges.amazonaws.com/ip-ranges.json"

custom:
  stages:
    - local
    - prod

functions:
  # health
  health-check:
    handler: health.check
    events:
      - http: GET /health/check
  # aws-ip-range-api
  aws-ip-range-api:
    handler: aws-ip-range.handler
    events:
      - http:
          path: /aws-ip-range/{ip}
          method: get
          cors: true

plugins:
  - serverless-python-requirements
