# serverless.yml

service: aws-ip-range # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage,'prod'}
  region: us-east-2
  environment:
    LOGGER_LEVEL: "DEBUG" # CRITICAL, ERROR, WARNING, INFO, DEBUG, NOTSET
    IP_RANGE_JSON_URL: "https://ip-ranges.amazonaws.com/ip-ranges.json"

custom:
  stages:
    - local
    - prod

functions:
  # health
  health-check:
    handler: health.check
    events:
      - http: GET /health/check
  # get-all-data
  get-all-data:
    handler: aws-ip-range.get_all_data
    events:
      - http:
          path: /{ip}
          method: get
          cors: true
  # get-region
  get-region:
    handler: aws-ip-range.get_region
    events:
      - http:
          path: /{ip}/region
          method: get
          cors: true
  # get-service
  get-service:
    handler: aws-ip-range.get_service
    events:
      - http:
          path: /{ip}/service
          method: get
          cors: true

plugins:
  - serverless-python-requirements
